### ISSUE TITLE
Document source for public keys

### ISSUE THREAD

**Issue by drewfarris** [fluo-io/fluo-dev#66]
I am experimenting with fluo-dev in a Docker container. After running `fluo-dev download`, I see the messages:

```
Verifying the authenticity of tarballs using gpg and downloaded signatures:

Verifying accumulo-1.7.1-bin.tar.gz
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: Signature made Mon 22 Feb 2016 09:32:43 PM UTC using RSA key ID 00B6899D
gpg: Can't check signature: No public key

verifying hadoop-2.6.3.tar.gz
gpg: Signature made Fri 18 Dec 2015 02:22:42 AM UTC using RSA key ID 526633F3
gpg: Can't check signature: No public key

Verifying zookeeper-3.4.6.tar.gz
gpg: Signature made Thu 20 Feb 2014 11:09:58 AM UTC using RSA key ID D2C80E32
gpg: Can't check signature: No public key

Verifying spark-1.5.1-bin-hadoop2.6.tgz
gpg: Signature made Thu 24 Sep 2015 06:13:27 AM UTC using RSA key ID FC8ED089
gpg: Can't check signature: No public key
```

If we are going to the trouble of doing a gpg verify, perhaps fluo-dev fetch and install the public keys into the appropriate public key ring?

**Comment by mikewalch** [comment]
Thanks for pointing this out.  I haven't liked how complicated this is for awhile.  A simpler solution is to  confirm that downloaded tarballs match configured MD5 hashes in env.sh (the configuration file for fluo-dev).  This is done in [fluo-io/zetten](https://github.com/fluo-io/zetten) and has worked well.  The default configuration file (env.sh.example) will have hashes for the default versions of software and user's can double check them before running `fluo-dev download` and use gpg verify on their own if they have any concerns.

**Comment by drewfarris** [comment]
@mikewalch this looks great. I tried it out and it works perfectly. It is nice that a second invocation of fluo-download won't attempt to re-download.

**Comment by mikewalch** [comment]
Download command no longer uses `gpg verify` after PR #67
